name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Upgrade NPM
        run: npm install -g npm

      - name: Install dependencies
        run: npm ci
      
      - name: Perform build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Archive built library
        uses: actions/upload-artifact@v3
        with:
          name: dom-builder
          path: dist